version: "3.9"

services:
  # MongoDB Service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db

  # Node.js/Express.js API Service
  paaumarket_api:
    build: .
    ports:
      - 3000:5000
    volumes:
      - .:/usr/src/app
    environment:
      PORT: 5000
      MONGODB_URI: mongodb://mongo_db:27017/paaumarket
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
