version: "3.9"

services:
  # MongoDB Service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db

  # Node.js/Express.js API Service
  paaumarket_api:
    build: .
    ports:
      - 3000:5000
    volumes:
      - .:/usr/src/app
    environment:
      PORT: 5000
      MONGODB_URI: mongodb://mongo_db:27017/paaumarket
      JWT_SECRET: "66ad0476-eb0f-4371-920b-0dc96b80441f"
      CLOUDINARY_COULDNAME: dsdvygpru
      CLOUDINARY_API_KEY: "389316621866671"
      CLOUDINARY_API_SECRET: Cq5lFENcKtgMDMTO6XR3x_8lO6s
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
