name: "Install Dependencies and Deploy"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/*]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Node.JS
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      # Cleanup

      - name: Cleanup git folders
        run: find . -type d -name ".git*" -prune -exec rm -rf {} +

      # Setup

      - name: Setup .gitignore files
        run: find . -type f -name ".gitdeploy.gitignore" -execdir mv {} .gitignore \;

      # Deploy

      - name: Deploy
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        with:
          user-email:
          create-target-branch-if-needed: true
          source-directory: "."
          destination-github-username: ${{ secrets.DEPLOY_GITHUB_USERNAME }}
          destination-repository-name: ${{ secrets.DEPLOY_GITHUB_REPO }}
